# Generated by Django 3.1.7 on 2021-03-22 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210319_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='instauser',
            name='subscriptions',
            field=models.ManyToManyField(related_name='followers', to='accounts.InstaUser', verbose_name='Подписки'),
        ),
    ]
