version: '3'

services:
  db:
    image: postgres:14.1
    volumes:
      - postgresql_data:/var/lib/postgresql/data/
    environment:
      - TZ=Asia/Almaty
      - POSTGRES_DB=djangogram_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5555:5555"
    restart: always

  web:
    build:
      context: ./
      dockerfile: Dockerfile
    command:
      - bash -c "python manage.py migrate --noinput && python manage.py collectstatic --noinput && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - web_volume:/home/app/web
      - media:/home/app/web/uploads
      - logs:/home/app/web/logs:rw
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - TZ=Asia/Almaty
    restart: always

volumes:
  postgresql_data:
  media:
    external: true
  logs:
    external: true
  web_volume:


