name: "Django deploy workflow"

on:
  push:
    branches:
      - master

jobs:
  deploy-job:
    runs-on: ubuntu-latest
    steps:
      - name: Install ssh key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: 'any_host'
      - name: rsync deployments
        uses: burnett01/rsync-deployments@5.2
        with:
          switches: -avzr --delete --exclude=.git/
          remote_path: ${{ secrets.REMOTE_FOLDER }}
          remote_host: ${{ secrets.SSH_HOST }}
          remote_user: ${{ secrets.SSH_USER }}
          remote_key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: clone repo and create environment
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            docker volume create --name=logs
            docker volume create --name=media
            docker volume create --name=static
            ls -a
            pwd
            cd projects/simpleGram/djangogram
            pwd
            mkdir -p logs
            mkdir -p media
            mkdir -p static
            docker-compose build
            docker-compose down --remove-orphans
            docker-compose up -d
            docker ps
            systemctl restart nginx
            exit
